from __future__ import annotations

from enum import StrEnum


class Language(StrEnum):
    ASSAMESE = "as"
    BENGALI = "bn"
    GUJARATI = "gu"
    HINDI = "hi"
    ENGLISH = "en"
    KANNADA = "kn"
    MALAYALAM = "ml"
    MARATHI = "mr"
    NEPALI = "ne"
    ODIA = "or"
    PUNJABI = "pa"
    SANSKRIT = "sa"
    TAMIL = "ta"
    TELUGU = "te"
    URDU = "ur"
    CODE_MIXED = "hi-en"
    UNKNOWN = "unknown"


class ChunkStrategy(StrEnum):
    ATOMIC = "atomic"
    SENTENCE_WINDOW = "sentence_window"
    SEMANTIC_SECTION = "semantic_section"
    PARENT_CHILD = "parent_child"
    BILINGUAL_PAIRED = "bilingual_paired"


class PipelineState(StrEnum):
    AUDIO_RECEIVED = "AUDIO_RECEIVED"
    STT_PARTIAL = "STT_PARTIAL"
    SPECULATIVE_RETRIEVAL = "SPECULATIVE_RETRIEVAL"
    STT_FINAL = "STT_FINAL"
    INPUT_GUARDED = "INPUT_GUARDED"
    RETRIEVED = "RETRIEVED"
    EVIDENCE_SELECTED = "EVIDENCE_SELECTED"
    ANSWERED = "ANSWERED"
    VERIFIED = "VERIFIED"
    COMPLETED = "COMPLETED"
    ABSTAINED = "ABSTAINED"
    NEEDS_REPEAT = "NEEDS_REPEAT"
    UNSAFE = "UNSAFE"
    DEADLINE_FALLBACK = "DEADLINE_FALLBACK"
    DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
    FAILED = "FAILED"


class GuardrailDecision(StrEnum):
    ALLOW = "ALLOW"
    ABSTAIN = "ABSTAIN"
    NEEDS_REPEAT = "NEEDS_REPEAT"
    BLOCK = "BLOCK"
    WARN = "WARN"


class GuardrailReason(StrEnum):
    LOW_STT_CONFIDENCE = "LOW_STT_CONFIDENCE"
    SILENCE = "SILENCE"
    AUDIO_TOO_SHORT = "AUDIO_TOO_SHORT"
    INVALID_AUDIO = "INVALID_AUDIO"
    NO_RELEVANT_EVIDENCE = "NO_RELEVANT_EVIDENCE"
    RETRIEVAL_DISAGREEMENT = "RETRIEVAL_DISAGREEMENT"
    STALE_CORPUS = "STALE_CORPUS"
    UNSAFE_REQUEST = "UNSAFE_REQUEST"
    PROMPT_INJECTION = "PROMPT_INJECTION"
    UNSUPPORTED_CLAIM = "UNSUPPORTED_CLAIM"
    DEADLINE_EXCEEDED = "DEADLINE_EXCEEDED"
    DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
    EMPTY_QUERY = "EMPTY_QUERY"


class ErrorCode(StrEnum):
    UNAUTHORIZED = "UNAUTHORIZED"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    DEADLINE_EXCEEDED = "DEADLINE_EXCEEDED"
    DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
    QDRANT_ERROR = "QDRANT_ERROR"
    SARVAM_ERROR = "SARVAM_ERROR"
    RETRIEVAL_ERROR = "RETRIEVAL_ERROR"
    GENERATION_ERROR = "GENERATION_ERROR"
    GROUNDING_FAILED = "GROUNDING_FAILED"
    CANCELLED = "CANCELLED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class AnswerMode(StrEnum):
    EXTRACTIVE = "extractive"
    LLAMA = "llama"
    EVIDENCE_FALLBACK = "evidence_fallback"
    ABSTENTION = "abstention"


class SynthesisStatus(StrEnum):
    COMPLETED = "completed"
    ABSTAINED = "abstained"
    TIMED_OUT = "timed_out"
    UNAVAILABLE = "unavailable"
    GROUNDING_FAILED = "grounding_failed"


class SttEventType(StrEnum):
    PARTIAL = "partial"
    FINAL = "final"
    ERROR = "error"
